### ISSUE TITLE
PiwikTracker sharedInstanceWithSiteID freezes main thread

### ISSUE THREAD

**Issue by aeirola** [PiwikPRO/piwik-pro-sdk-framework-ios#2]
Using the SDK version 1.0.3 or later seems to freeze whenever `PiwikTracker sharedInstanceWithSiteID` is called after `didFinishLaunchingWithOptions`. This is reproducible in the Demo app (https://github.com/PiwikPRO/piwik-pro-sdk-demo-ios) by just upgrading the SDK pod to 1.0.3 or later. The issue doesn't seem to be present in version 1.0.1.

**Comment by aeirola** [comment]
In case anyone is maintaining this repository, I noticed that the old version of the SDK seems to be using the older `UIWebView` for something, since adding the SDK caused Apple App Store Connect to send a warning email stating

> TMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 

I would imagine that newer versions of the SDK would have already moved to WKWebView, but as the newer versions of the SDK have issues with initialisation we are not able to update at the moment.

**Comment by zaan** [comment]
Thanks for the information about the issue. It will be investigated.

**Comment by DreamEmulator** [comment]
@aeirola this bug seems to have been fixed: https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios/commit/e75fad87c802905fcc39f25e2828e38535115bba

**Comment by aeirola** [comment]
Yeah, this seems to be fixed now. Thanks Andrzej Mironowicz!
